name: Finch CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:8.7.0-alpine
    services:
      mongofinch:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install dependencies and run tests
        working-directory: ./comprehend-service
        run: |
          npm install
          npm test
        env:
          dbURI: mongodb://mongofinch:27017/finch

  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag comprehend worker
        working-directory: ./comprehend-service
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/comprehend:0.0.2 .

      - name: Push the image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/comprehend:0.0.2
